import { Address } from 'set-protocol-utils';

// Generated by mnemonic "candy maple cake sugar pudding cream honey rich booboo crumble sweet treat"
export interface Account {
  address: Address;
  privateKey: string;
}
const NULL_ADDRESS = '0x0000000000000000000000000000000000000000';

const ACCOUNTS: Account[] = [
  {
    address: '0x2428b6c0ba3e38dba1362d1912505566a714d043',
    privateKey: '0d858e4073946296f89a4c850a113aad82b607bd25c50d3c71fd24395fdf28b8',
  },
  {
    address: '0x2172def2a99133b6259249728ff8b289efe32c34',
    privateKey: '7d6e63336587fade9a71e8a3c6c61bf2d356ef779281e596d42852cbb000bc8a',
  },
  {
    address: '0x0326f5e888120d7dca54f578898cfc6958c3cf95',
    privateKey: '6bc735a4c2ca72607dbd6f7f8dac8656979071717c3413e8ecabc9f5140140ac',
  },
  {
    address: '0xce0cc750757a3790ed89e536f826251a37f274b1',
    privateKey: 'fa9cd495347a3815289c2fad805f779424d6b0d99fd811d3760ef7f375561584',
  },
  {
    address: '0x0a7c03e53c1fa7b7a3fd59eda212e6477d80428d',
    privateKey: '8fec6f5c7a3f37a1a5d4eda1848f62330e48bcce8fe0d545e8dfd26d1a470992',
  },
  {
    address: '0xea6d80ff2ce31877732d84225adf4cd922f6f963',
    privateKey: '419ae035c0eca3ff508fed8b16102f2faf39b04bf058bed439273bf197b23494',
  },
  {
    address: '0x270a3ff32df2165588a343f4ae3ea3789786744a',
    privateKey: 'adf4123cad123d06591624f4355c8adfd80c0fe1b3874136631c885e5bc2ba72',
  },
  {
    address: '0x54c890990b07c737c6e99db713c7b47a316c6e0d',
    privateKey: '03d500afedcac8cc3cd88becb90ec7d1c3369799a834af37d27b52143853c135',
  },
  {
    address: '0x024f6fe33321cbf6056da20f88180b8ab742a9d6',
    privateKey: 'aa12d5cd2862fa1a53235bc6d1b67fdd37a568f06883a03864c93b4e5644313c',
  },
  {
    address: '0xa20522b136fabf224955a34a3a51628f848f7bad',
    privateKey: '93988474f1a56ee50b4ee751c687f2b7010f5a614217f1eaecfd373610d3686b',
  },
];

const DEFAULT_ACCOUNT = ACCOUNTS[0].address;

export { ACCOUNTS, DEFAULT_ACCOUNT, NULL_ADDRESS };
