import { Address } from 'set-protocol-utils';

// Generated by mnemonic "candy maple cake sugar pudding cream honey rich booboo crumble sweet treat"
export interface Account {
  address: Address;
  privateKey: string;
}
const NULL_ADDRESS = '0x0000000000000000000000000000000000000000';

const ACCOUNTS: Account[] = [
  {
    address: '0x5409ED021D9299bf6814279A6A1411A7e866A631',
    privateKey: '0xf2f48ee19680706196e2e339e5da3491186e0c4c5030670656b0e0164837257d',
  },
  {
    address: '0x6Ecbe1DB9EF729CBe972C83Fb886247691Fb6beb',
    privateKey: '0x5d862464fe9303452126c8bc94274b8c5f9874cbd219789b3eb2128075a76f72',
  },
  {
    address: '0xE36Ea790bc9d7AB70C55260C66D52b1eca985f84',
    privateKey: '0xdf02719c4df8b9b8ac7f551fcb5d9ef48fa27eef7a66453879f4d8fdc6e78fb1',
  },
  {
    address: '0xE834EC434DABA538cd1b9Fe1582052B880BD7e63',
    privateKey: '0xff12e391b79415e941a94de3bf3a9aee577aed0731e297d5cfa0b8a1e02fa1d0',
  },
  {
    address: '0x78dc5d2d739606d31509c31d654056a45185ecb6',
    privateKey: '0x752dd9cf65e68cfaba7d60225cbdbc1f4729dd5e5507def72815ed0d8abc6249',
  },
  {
    address: '0xa8dda8d7f5310e4a9e24f8eba77e091ac264f872',
    privateKey: '0xefb595a0178eb79a8df953f87c5148402a224cdf725e88c0146727c6aceadccd',
  },
  {
    address: '0x06cef8e666768cc40cc78cf93d9611019ddcb628',
    privateKey: '0x83c6d2cc5ddcf9711a6d59b417dc20eb48afd58d45290099e5987e3d768f328f',
  },
  {
    address: '0x4404ac8bd8f9618d27ad2f1485aa1b2cfd82482d',
    privateKey: '0xbb2d3f7c9583780a7d3904a2f55d792707c345f21de1bacb2d389934d82796b2',
  },
  {
    address: '0x7457d5e02197480db681d3fdf256c7aca21bdc12',
    privateKey: '0xb2fd4d29c1390b71b8795ae81196bfd60293adf99f9d32a0aff06288fcdac55f',
  },
  {
    address: '0x91c987bf62d25945db517bdaa840a6c661374402',
    privateKey: '0x23cb7121166b9a2f93ae0b7c05bde02eae50d64449b2cbb42bc84e9d38d6cc89',
  },
];

const DEFAULT_ACCOUNT = ACCOUNTS[0].address;

export { ACCOUNTS, DEFAULT_ACCOUNT, NULL_ADDRESS };
